
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/hospital3119009062liulong?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 6000
#打印输出日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 8080






